# ===============================
# DATABASE CONFIGURATION
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flipkart_db
    username: root
    password: Test@12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
